#
# Autogenerated by Thrift
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#


module Messagebus
  module Thrift
        module MessagePayloadType
          JSON = 1
          BINARY = 2
          STRING = 3
          VALUE_MAP = {1 => "JSON", 2 => "BINARY", 3 => "STRING"}
          VALID_VALUES = Set.new([JSON, BINARY, STRING]).freeze
        end

        class MessagePayload
          include ::Thrift::Struct, ::Thrift::Struct_Union
          MESSAGEFORMAT = 1
          STRINGPAYLOAD = 2
          BINARYPAYLOAD = 3

          FIELDS = {
            MESSAGEFORMAT => {:type => ::Thrift::Types::I32, :name => 'messageFormat', :enum_class => Messagebus::Thrift::MessagePayloadType},
            STRINGPAYLOAD => {:type => ::Thrift::Types::STRING, :name => 'stringPayload', :optional => true},
            BINARYPAYLOAD => {:type => ::Thrift::Types::STRING, :name => 'binaryPayload', :binary => true, :optional => true}
          }

          def struct_fields; FIELDS; end

          def binary?
            @messageFormat == Messagebus::Thrift::MessagePayloadType::BINARY
          end

          def json?
            @messageFormat == Messagebus::Thrift::MessagePayloadType::JSON
          end

          def string?
            @messageFormat == Messagebus::Thrift::MessagePayloadType::STRING
          end

          def validate
            raise ::Thrift::ProtocolException.new(::Thrift::ProtocolException::UNKNOWN, 'Required field messageFormat is unset!') unless @messageFormat
            unless @messageFormat.nil? || Messagebus::Thrift::MessagePayloadType::VALID_VALUES.include?(@messageFormat)
              raise ::Thrift::ProtocolException.new(::Thrift::ProtocolException::UNKNOWN, 'Invalid value of field messageFormat!')
            end
          end

          ::Thrift::Struct.generate_accessors self
        end

        class MessageInternal
          include ::Thrift::Struct, ::Thrift::Struct_Union
          MESSAGEID = 1
          PAYLOAD = 2
          PROPERTIES = 3

          FIELDS = {
            MESSAGEID => {:type => ::Thrift::Types::STRING, :name => 'messageId'},
            PAYLOAD => {:type => ::Thrift::Types::STRUCT, :name => 'payload', :class => Messagebus::Thrift::MessagePayload},
            PROPERTIES => {:type => ::Thrift::Types::MAP, :name => 'properties', :key => {:type => ::Thrift::Types::STRING}, :value => {:type => ::Thrift::Types::STRING}, :optional => true}
          }

          def struct_fields; FIELDS; end

          def validate
            raise ::Thrift::ProtocolException.new(::Thrift::ProtocolException::UNKNOWN, 'Required field messageId is unset!') unless @messageId
            raise ::Thrift::ProtocolException.new(::Thrift::ProtocolException::UNKNOWN, 'Required field payload is unset!') unless @payload
          end

          ::Thrift::Struct.generate_accessors self
        end

      end
    end
